---
environment:
  matrix:
  # Ruby 2.4 (32bit)
  - ruby_version: "24"
    PYTHONDIR: "C:\\Python27"
    PYTHON: "C:\\Python27\\python.exe"

  - ruby_version: "24"
    PYTHONDIR: "C:\\Python34"
    PYTHON: "C:\\Python34\\python.exe"

  - ruby_version: "24"
    PYTHONDIR: "C:\\Python35"
    PYTHON: "C:\\Python35\\python.exe"

  - ruby_version: "24"
    PYTHONDIR: "C:\\Python36"
    PYTHON: "C:\\Python36\\python.exe"

  # Ruby 2.4 (64bit)
  - ruby_version: "24-x64"
    PYTHONDIR: "C:\\Python27-x64"
    PYTHON: "C:\\Python27-x64\\python.exe"

  - ruby_version: "24-x64"
    PYTHONDIR: "C:\\Python34-x64"
    PYTHON: "C:\\Python34-x64\\python.exe"

  - ruby_version: "24-x64"
    PYTHONDIR: "C:\\Python35-x64"
    PYTHON: "C:\\Python35-x64\\python.exe"

  - ruby_version: "24-x64"
    PYTHONDIR: "C:\\Python36-x64"
    PYTHON: "C:\\Python36-x64\\python.exe"

  # Ruby 2.3 (32bit)
  - ruby_version: "23"
    PYTHONDIR: "C:\\Python27"
    PYTHON: "C:\\Python27\\python.exe"

  - ruby_version: "23"
    PYTHONDIR: "C:\\Python34"
    PYTHON: "C:\\Python34\\python.exe"

  - ruby_version: "23"
    PYTHONDIR: "C:\\Python35"
    PYTHON: "C:\\Python35\\python.exe"

  - ruby_version: "23"
    PYTHONDIR: "C:\\Python36"
    PYTHON: "C:\\Python36\\python.exe"

  # Ruby 2.3 (64bit)
  - ruby_version: "23-x64"
    PYTHONDIR: "C:\\Python27-x64"
    PYTHON: "C:\\Python27-x64\\python.exe"

  - ruby_version: "23-x64"
    PYTHONDIR: "C:\\Python34-x64"
    PYTHON: "C:\\Python34-x64\\python.exe"

  - ruby_version: "23-x64"
    PYTHONDIR: "C:\\Python35-x64"
    PYTHON: "C:\\Python35-x64\\python.exe"

  - ruby_version: "23-x64"
    PYTHONDIR: "C:\\Python36-x64"
    PYTHON: "C:\\Python36-x64\\python.exe"

branches:
  only:
    - master
    - /release-.*/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

deploy: off
build: off

install:
  - "SET PATH=%PYTHONDIR%;%PYTHONDIR%\\Scripts;%PATH%"
  - "SET PATH=C:\\Ruby%ruby_version%\\bin;%PATH%"
  - "bundle install"
  - "pip install numpy"

before_test:
  - "bundle exec rake -rdevkit clobber compile"
  - ECHO "=== python investigator.py ==="
  - "python lib\\pycall\\python\\investigator.py"

test_script:
  - "SET PYCALL_DEBUG_FIND_LIBPYTHON=1"
  - rake

matrix:
  allow_failures:
  - PYTHONDIR: "C:\\Python27"
  - PYTHONDIR: "C:\\Python27-x64"
